version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: npm run test -- --progress=false --watch=false --browsers=ChromeHeadlessCI
  deploy:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: echo "this is the deploy job"
workflows:
  version: 2
  build-test-and-approval-deploy:
    jobs:
      - build  
      - test: 
          requires: 
            - build
      - hold: 
          type: approval 
          requires: 
           - test
      - deploy:
          requires:
            - hold